### ISSUE TITLE
Build shortcuts not working on gedit 3.34.1

### ISSUE THREAD

**Issue by Marathon2112** [rjdsc/gedit-latex-external-tools#1]
When using build shortcuts (Tools -> LaTeX Tools), the following error message is returned:
```
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/latex/tools/__init__.py", line 133, in run_tool
    self._runner.run(context.active_editor.file, self._tool, tool_view)
  File "/usr/lib/gedit/plugins/latex/latex/editor.py", line 385, in file
    if self._document_is_master:
AttributeError: 'LaTeXEditor' object has no attribute '_document_is_master'
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/latex/tools/__init__.py", line 133, in run_tool
    self._runner.run(context.active_editor.file, self._tool, tool_view)
  File "/usr/lib/gedit/plugins/latex/latex/editor.py", line 385, in file
    if self._document_is_master:
AttributeError: 'LaTeXEditor' object has no attribute '_document_is_master'
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/latex/tools/__init__.py", line 133, in run_tool
    self._runner.run(context.active_editor.file, self._tool, tool_view)
  File "/usr/lib/gedit/plugins/latex/latex/editor.py", line 385, in file
    if self._document_is_master:
AttributeError: 'LaTeXEditor' object has no attribute '_document_is_master'
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/latex/tools/__init__.py", line 133, in run_tool
    self._runner.run(context.active_editor.file, self._tool, tool_view)
  File "/usr/lib/gedit/plugins/latex/latex/editor.py", line 385, in file
    if self._document_is_master:
AttributeError: 'LaTeXEditor' object has no attribute '_document_is_master'
```

**Comment by Marathon2112** [comment]
Sorry wrong repo.
